version: '3.9'
services:
  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: abyss
      POSTGRES_PASSWORD: abyss
      POSTGRES_DB: abyss_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abyss -d abyss_test"]
      interval: 3s
      timeout: 3s
      retries: 20
