name: Mobile App CI/CD

on:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ feature/workflows ]

env:
  NODE_VERSION: 'lts/*'
  W_DIRECTORY: './tests/mobile_workflow'

jobs:
  test:
    name: Test & Lint - Build Android Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm ci

      - name: Lint
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm run lint

      - name: Run unit tests
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm test
        
  android-build:
    name: Build Android Debug
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm ci
        
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'wrapper'

      - name: Build APK with Gradle
        working-directory: ${{ env.W_DIRECTORY }}
        run: gradle build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.W_DIRECTORY }}/android/app/build/outputs/apk/debug/*.apk
          retention-days: 7
