name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

env:
  NODE_VERSION: 'lts/*'
  W_DIRECTORY: './api'
  DIST_DIRECTORY: './api/dist'

jobs:
  build-and-deploy:
    name: Build & Deploy API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm ci

      - name: Build TypeScript
        working-directory: ${{ env.W_DIRECTORY }}
        run: npm run build

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp -r ${{ env.DIST_DIRECTORY }} deploy/dist
          cp ${{ env.W_DIRECTORY }}/package*.json deploy/
          cp ${{ env.W_DIRECTORY }}/.env.example deploy/.env || echo "Pas de .env.example"
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./deploy/
          server-dir: /api/
